name: Sync from Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_from_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Prevent Infinite Loop
        run: |
          if [[ "${{ github.actor }}" == "github-actions" ]]; then
            echo "Workflow triggered by github-actions, skipping push..."
            exit 0
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Fork Repository as Remote
        run: |
          git remote add fork https://github.com/JonathanKenZ/notebook.git
          git fetch fork

      - name: Attempt Merge Changes from Fork
        id: merge
        continue-on-error: true
        run: |
          git checkout main
          if git merge fork/main --allow-unrelated-histories --no-edit; then
            echo "MERGE_STATUS=0" >> $GITHUB_ENV
          else
            echo "MERGE_STATUS=1" >> $GITHUB_ENV
          fi
          
      - name: Check for Merge Conflicts
        if: env.MERGE_STATUS != '0'
        run: |
          echo "❌ Merge conflict detected, creating a Pull Request"
          git merge --abort
      - name: Generate Unique Branch Name
        if: env.MERGE_STATUS == '1'
        run: |
          echo "BRANCH_NAME=conflict-fix-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          
      - name: Create Conflict Branch
        if: env.MERGE_STATUS != '0'
        run: |
          git checkout -b ${{ BRANCH_NAME }}
          git push origin HEAD

      - name: Create Pull Request
        if: env.MERGE_STATUS != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "⚠️ Auto Merge Conflict Detected - Manual Resolution Required"
          body: |
            This PR was created automatically because a merge conflict was detected during synchronization.
            Please review and resolve the conflict manually.
          branch: ${{ BRANCH_NAME }}
          base: main
          
      - name: Push Merged Changes to Main
        if: env.MERGE_STATUS == '0'
        env:
          MAIN_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ChickenHu/notebook.git main
