name: Sync from Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_from_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Prevent Infinite Loop
        run: |
          if [[ "${{ github.actor }}" == "github-actions" ]]; then
            echo "Workflow triggered by github-actions, skipping push..."
            exit 0
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Fork Repository as Remote
        run: |
          git remote add fork https://github.com/JonathanKenZ/notebook.git
          git fetch fork

      - name: Merge Changes from Fork
        run: |
          git checkout main
          git merge fork/main --no-edit || echo "Merge conflicts detected"

      - name: Push Merged Changes to Main
        env:
          MAIN_PAT: ${{ secrets.MAIN_PAT }}
        run: |
          git push https://$MAIN_PAT@github.com/ChickenHu/notebook.git main
